"""Анхны схем — Postgres дээрх бүх хүснэгт, индекс.

Моделиос (`app/models.py`) autogenerate-ээр гарч, ГАРААР шалгагдсан:

  · МӨНГӨ нь `double precision` (Float) — SQLite дээрхтэй ЯГ ижил хэлбэр.
    Numeric руу ХӨРВҮҮЛЭЭГҮЙ: тооцооны бүх дүрэм, бөөрөнхийлөлт (`round(x, 2)`)
    өнөөдрийн float дээр бичигдсэн, 890 тест түүн дээр зогсож байна.
    Хөрвүүлэлт нь тусдаа, өөрийн шалгууртай ажил.
  · Огноо нь `date`, цагийн тэмдэг нь `timestamp WITHOUT time zone` —
    `datetime.utcnow()` нь наив UTC хадгалдаг тул хэлбэр нь таарна.
  · Загварын 2 индекс (`ix_stock_adjustments_material`, `ix_notes_entity`)
    ба 8 давхардлын хориг (unique) autogenerate-ээр орсон.
  · Түүн дээр нэмээд FK багана БҮРД индекс (доор). SQLite дээр жижиг сан
    бүрэн скан хийхэд асуудалгүй байсан; Postgres дээр `client_id`-аар
    шүүх бүрд seq scan хийвэл харилцагчийн дэлгэц секундээр удаашрана.
    Postgres нь PK-д индекс өөрөө үүсгэдэг ч ГАДААД түлхүүрт ҮГҮЙ.

Revision ID: 5dc8c7e8f82c
Revises:
Create Date: 2026-09-06
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5dc8c7e8f82c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('reg', sa.String(length=20), nullable=False),
    sa.Column('person', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('monthly_salary', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('ndsh', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('monthly_rate', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('repair_fee', sa.Float(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=12), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_entity', 'notes', ['entity_type', 'entity_id'], unique=False)
    op.create_table('salary_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('half', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Integer(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('ndsh_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'half')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('phone2', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('ref', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('promise_date', sa.Date(), nullable=True),
    sa.Column('promise_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('billing_from', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('cycle_days', sa.Integer(), nullable=False),
    sa.Column('cycle_mode', sa.String(length=10), nullable=False),
    sa.Column('penalty_percent', sa.Float(), nullable=False),
    sa.Column('deposit', sa.Float(), nullable=False),
    sa.Column('deposit_status', sa.String(length=12), nullable=False),
    sa.Column('deposit_returned', sa.Float(), nullable=False),
    sa.Column('deposit_applied', sa.Float(), nullable=False),
    sa.Column('deposit_settled_date', sa.Date(), nullable=True),
    sa.Column('vat_percent', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no')
    )
    op.create_table('loan_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('part', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.String(length=30), nullable=False),
    sa.Column('client', sa.String(length=150), nullable=False),
    sa.Column('d_from', sa.Date(), nullable=False),
    sa.Column('d_to', sa.Date(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('vat', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no')
    )
    op.create_table('machine_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entry', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('client', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_grade_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('nb_price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'grade_id')
    )
    op.create_table('notification_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snooze_until', sa.Date(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'entity_id')
    )
    op.create_table('salary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base', sa.Float(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('ndsh_amount', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['salary_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('before', sa.Float(), nullable=False),
    sa.Column('after', sa.Float(), nullable=False),
    sa.Column('diff', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('stocktake_batch', sa.String(length=40), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_adjustments_material', 'stock_adjustments', ['material_id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Float(), nullable=False),
    sa.Column('on_rent', sa.Float(), nullable=False),
    sa.Column('in_repair', sa.Float(), nullable=False),
    sa.Column('written_off', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'grade_id')
    )
    op.create_table('akt_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.String(length=30), nullable=False),
    sa.Column('cycle_start', sa.Date(), nullable=False),
    sa.Column('cycle_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('rent_amount', sa.Float(), nullable=False),
    sa.Column('charge_amount', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('paid', sa.Float(), nullable=False),
    sa.Column('penalty_booked', sa.Float(), nullable=False),
    sa.Column('penalty_paid', sa.Float(), nullable=False),
    sa.Column('penalty_booked_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_entry_id', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.Column('agreed_at', sa.Date(), nullable=True),
    sa.Column('agreed_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['client_entry_id'], ['client_entries.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('barter_desc', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_entry_id', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['client_entry_id'], ['client_entries.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('old_rate', sa.Float(), nullable=True),
    sa.Column('new_rate', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barter_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('date_in', sa.Date(), nullable=False),
    sa.Column('value_in', sa.Float(), nullable=False),
    sa.Column('asking_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('sold_amount', sa.Float(), nullable=False),
    sa.Column('sold_to', sa.String(length=150), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=False),
    sa.Column('voided_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('issue_line_id', sa.Integer(), nullable=True),
    sa.Column('return_grade_id', sa.Integer(), nullable=True),
    sa.Column('billed_days_override', sa.Integer(), nullable=True),
    sa.Column('days_confirmed', sa.Integer(), nullable=False),
    sa.Column('repair_qty', sa.Float(), nullable=False),
    sa.Column('repair_fee', sa.Float(), nullable=False),
    sa.Column('writeoff_qty', sa.Float(), nullable=False),
    sa.Column('writeoff_fee', sa.Float(), nullable=False),
    sa.Column('sale_fee', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['issue_line_id'], ['movement_lines.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['return_grade_id'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('part', sa.String(length=10), nullable=False),
    sa.Column('manual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ---- Гадаад түлхүүрийн индексүүд (41 багана) ----
    op.create_index('ix_akt_entries_contract_id', 'akt_entries', ['contract_id'])
    op.create_index('ix_barter_assets_client_id', 'barter_assets', ['client_id'])
    op.create_index('ix_barter_assets_payment_id', 'barter_assets', ['payment_id'])
    op.create_index('ix_client_contacts_client_id', 'client_contacts', ['client_id'])
    op.create_index('ix_client_entries_client_id', 'client_entries', ['client_id'])
    op.create_index('ix_collection_notes_client_id', 'collection_notes', ['client_id'])
    op.create_index('ix_contract_items_contract_id', 'contract_items', ['contract_id'])
    op.create_index('ix_contract_items_material_id', 'contract_items', ['material_id'])
    op.create_index('ix_contract_items_grade_id', 'contract_items', ['grade_id'])
    op.create_index('ix_contracts_client_id', 'contracts', ['client_id'])
    op.create_index('ix_deposit_events_contract_id', 'deposit_events', ['contract_id'])
    op.create_index('ix_deposit_events_payment_id', 'deposit_events', ['payment_id'])
    op.create_index('ix_invoices_contract_id', 'invoices', ['contract_id'])
    op.create_index('ix_invoices_client_entry_id', 'invoices', ['client_entry_id'])
    op.create_index('ix_loan_payments_loan_id', 'loan_payments', ['loan_id'])
    op.create_index('ix_machine_invoices_machine_id', 'machine_invoices', ['machine_id'])
    op.create_index('ix_machine_logs_machine_id', 'machine_logs', ['machine_id'])
    op.create_index('ix_material_grade_prices_material_id', 'material_grade_prices', ['material_id'])
    op.create_index('ix_material_grade_prices_grade_id', 'material_grade_prices', ['grade_id'])
    op.create_index('ix_movement_lines_movement_id', 'movement_lines', ['movement_id'])
    op.create_index('ix_movement_lines_material_id', 'movement_lines', ['material_id'])
    op.create_index('ix_movement_lines_grade_id', 'movement_lines', ['grade_id'])
    op.create_index('ix_movement_lines_issue_line_id', 'movement_lines', ['issue_line_id'])
    op.create_index('ix_movement_lines_return_grade_id', 'movement_lines', ['return_grade_id'])
    op.create_index('ix_movements_contract_id', 'movements', ['contract_id'])
    op.create_index('ix_notification_states_user_id', 'notification_states', ['user_id'])
    op.create_index('ix_payment_allocations_payment_id', 'payment_allocations', ['payment_id'])
    op.create_index('ix_payment_allocations_invoice_id', 'payment_allocations', ['invoice_id'])
    op.create_index('ix_payments_client_id', 'payments', ['client_id'])
    op.create_index('ix_payments_contract_id', 'payments', ['contract_id'])
    op.create_index('ix_payments_client_entry_id', 'payments', ['client_entry_id'])
    op.create_index('ix_penalty_charges_contract_id', 'penalty_charges', ['contract_id'])
    op.create_index('ix_penalty_charges_client_id', 'penalty_charges', ['client_id'])
    op.create_index('ix_rate_changes_contract_id', 'rate_changes', ['contract_id'])
    op.create_index('ix_rate_changes_material_id', 'rate_changes', ['material_id'])
    op.create_index('ix_rate_changes_grade_id', 'rate_changes', ['grade_id'])
    op.create_index('ix_salary_items_run_id', 'salary_items', ['run_id'])
    op.create_index('ix_salary_items_employee_id', 'salary_items', ['employee_id'])
    op.create_index('ix_stock_adjustments_grade_id', 'stock_adjustments', ['grade_id'])
    op.create_index('ix_stocks_material_id', 'stocks', ['material_id'])
    op.create_index('ix_stocks_grade_id', 'stocks', ['grade_id'])


def downgrade() -> None:
    op.drop_index('ix_stocks_grade_id', table_name='stocks')
    op.drop_index('ix_stocks_material_id', table_name='stocks')
    op.drop_index('ix_stock_adjustments_grade_id', table_name='stock_adjustments')
    op.drop_index('ix_salary_items_employee_id', table_name='salary_items')
    op.drop_index('ix_salary_items_run_id', table_name='salary_items')
    op.drop_index('ix_rate_changes_grade_id', table_name='rate_changes')
    op.drop_index('ix_rate_changes_material_id', table_name='rate_changes')
    op.drop_index('ix_rate_changes_contract_id', table_name='rate_changes')
    op.drop_index('ix_penalty_charges_client_id', table_name='penalty_charges')
    op.drop_index('ix_penalty_charges_contract_id', table_name='penalty_charges')
    op.drop_index('ix_payments_client_entry_id', table_name='payments')
    op.drop_index('ix_payments_contract_id', table_name='payments')
    op.drop_index('ix_payments_client_id', table_name='payments')
    op.drop_index('ix_payment_allocations_invoice_id', table_name='payment_allocations')
    op.drop_index('ix_payment_allocations_payment_id', table_name='payment_allocations')
    op.drop_index('ix_notification_states_user_id', table_name='notification_states')
    op.drop_index('ix_movements_contract_id', table_name='movements')
    op.drop_index('ix_movement_lines_return_grade_id', table_name='movement_lines')
    op.drop_index('ix_movement_lines_issue_line_id', table_name='movement_lines')
    op.drop_index('ix_movement_lines_grade_id', table_name='movement_lines')
    op.drop_index('ix_movement_lines_material_id', table_name='movement_lines')
    op.drop_index('ix_movement_lines_movement_id', table_name='movement_lines')
    op.drop_index('ix_material_grade_prices_grade_id', table_name='material_grade_prices')
    op.drop_index('ix_material_grade_prices_material_id', table_name='material_grade_prices')
    op.drop_index('ix_machine_logs_machine_id', table_name='machine_logs')
    op.drop_index('ix_machine_invoices_machine_id', table_name='machine_invoices')
    op.drop_index('ix_loan_payments_loan_id', table_name='loan_payments')
    op.drop_index('ix_invoices_client_entry_id', table_name='invoices')
    op.drop_index('ix_invoices_contract_id', table_name='invoices')
    op.drop_index('ix_deposit_events_payment_id', table_name='deposit_events')
    op.drop_index('ix_deposit_events_contract_id', table_name='deposit_events')
    op.drop_index('ix_contracts_client_id', table_name='contracts')
    op.drop_index('ix_contract_items_grade_id', table_name='contract_items')
    op.drop_index('ix_contract_items_material_id', table_name='contract_items')
    op.drop_index('ix_contract_items_contract_id', table_name='contract_items')
    op.drop_index('ix_collection_notes_client_id', table_name='collection_notes')
    op.drop_index('ix_client_entries_client_id', table_name='client_entries')
    op.drop_index('ix_client_contacts_client_id', table_name='client_contacts')
    op.drop_index('ix_barter_assets_payment_id', table_name='barter_assets')
    op.drop_index('ix_barter_assets_client_id', table_name='barter_assets')
    op.drop_index('ix_akt_entries_contract_id', table_name='akt_entries')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_allocations')
    op.drop_table('movement_lines')
    op.drop_table('deposit_events')
    op.drop_table('barter_assets')
    op.drop_table('rate_changes')
    op.drop_table('penalty_charges')
    op.drop_table('payments')
    op.drop_table('movements')
    op.drop_table('invoices')
    op.drop_table('contract_items')
    op.drop_table('akt_entries')
    op.drop_table('stocks')
    op.drop_index('ix_stock_adjustments_material', table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    op.drop_table('salary_items')
    op.drop_table('notification_states')
    op.drop_table('material_grade_prices')
    op.drop_table('machine_logs')
    op.drop_table('machine_invoices')
    op.drop_table('loan_payments')
    op.drop_table('contracts')
    op.drop_table('collection_notes')
    op.drop_table('client_entries')
    op.drop_table('client_contacts')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('salary_runs')
    op.drop_index('ix_notes_entity', table_name='notes')
    op.drop_table('notes')
    op.drop_table('materials')
    op.drop_table('machines')
    op.drop_table('loans')
    op.drop_table('grades')
    op.drop_table('employees')
    op.drop_table('clients')
    op.drop_table('audit_logs')
    op.drop_table('attachments')
    # ### end Alembic commands ###
